// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCo1u6hKSQ-yT9STdLubJGSqT7Ni96w0E',
    appId: '1:548330753379:web:45610e24a8415f72501756',
    messagingSenderId: '548330753379',
    projectId: 'project-akhir-sanbercode',
    authDomain: 'project-akhir-sanbercode.firebaseapp.com',
    storageBucket: 'project-akhir-sanbercode.firebasestorage.app',
    measurementId: 'G-BZ671Q9BY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0SQ3vqu10zKR-HLDmL5SlbAx3pPkOZE',
    appId: '1:548330753379:android:068a204a359f75fd501756',
    messagingSenderId: '548330753379',
    projectId: 'project-akhir-sanbercode',
    storageBucket: 'project-akhir-sanbercode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOOcLi1WqRf239AXqhw-_2dGLb7c0k5E',
    appId: '1:548330753379:ios:6b197194d9bfc709501756',
    messagingSenderId: '548330753379',
    projectId: 'project-akhir-sanbercode',
    storageBucket: 'project-akhir-sanbercode.firebasestorage.app',
    iosBundleId: 'com.projectakhirflutterbootcamp.projectAkhirFlutterBootcamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXOOcLi1WqRf239AXqhw-_2dGLb7c0k5E',
    appId: '1:548330753379:ios:6b197194d9bfc709501756',
    messagingSenderId: '548330753379',
    projectId: 'project-akhir-sanbercode',
    storageBucket: 'project-akhir-sanbercode.firebasestorage.app',
    iosBundleId: 'com.projectakhirflutterbootcamp.projectAkhirFlutterBootcamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCo1u6hKSQ-yT9STdLubJGSqT7Ni96w0E',
    appId: '1:548330753379:web:904ca8a7a2fcec20501756',
    messagingSenderId: '548330753379',
    projectId: 'project-akhir-sanbercode',
    authDomain: 'project-akhir-sanbercode.firebaseapp.com',
    storageBucket: 'project-akhir-sanbercode.firebasestorage.app',
    measurementId: 'G-VCQ2MZJCEG',
  );
}
